{
 "title": "Custom Grafana dashboard",
 "description": "Visualizes the metrics collected by Prometheus.",
 "tags": [
  "linux",
  "node-exporter",
  "ops"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(node_time_seconds{job=\"$job\"},instance)"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_boot_time_seconds,job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Load | $host",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "repeat": "host",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (mode) (irate(node_cpu_seconds_total{instance=~\"$host\"}[5m]))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Network Traffic | $host",
   "type": "histogram",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 6 },
   "repeat": "host",
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=~\"$host\",device=~\"(?i)^(ens|eth).+$\"}[5m])  > 0",
     "legendFormat": "IN ({{device}})"
    },
    {
     "expr": "- irate(node_network_transmit_bytes_total{instance=~\"$host\",device=~\"(?i)^(ens|eth).+$\"}[5m]) < 0",
     "legendFormat": "OUT ({{device}})"
    }
   ]
  },
  {
   "title": "Memory Use",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 6 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - node_memory_MemFree_bytes{instance=~\"$host\"} / node_memory_MemTotal_bytes{instance=~\"$host\"}"
    }
   ]
  },
  {
   "title": "Disk Free (Total)",
   "type": "gauge",
   "description": "Free diskspace",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 13 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "1 - (sum(node_filesystem_free_bytes{instance=~\"$host\"}) / sum(node_filesystem_size_bytes{instance=~\"$host\"}))"
    }
   ]
  },
  {
   "title": "Disk (Free)",
   "type": "table",
   "gridPos": { "h": 6, "w": 19, "x": 5, "y": 13 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{fstype!~\"(tmpfs|rootfs).*\",instance=~\"$host\"}"
    }
   ]
  }
 ]
}